### ISSUE TITLE
HTML changes

### ISSUE THREAD

**Issue by JamesvanHoke** [Danomiterock/Save-My-HaHa#15]
- Set up HTML elements so they line up vertically instead of horizontally
- create border elements
- create a container to display our favorite gifs in
- create a container to display our favorite jokes in
- set up button locations
- assign id's to favorite jokes/gifs buttons

**Comment by spicystephy** [comment]
line 8, script, var jokeHolder = $("testJokeHolder") did not have # like line 7 (gifHolder), added it in
